apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -c
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: openssh
  name: openssh
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openssh
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -c
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: openssh
    spec:
      containers:
        - env:
            - name: OPENSSH_ROOT_PASSWORD
              value: ${OPENSSH_ROOT_PASSWORD:?OPENSSH_ROOT_PASSWORD}
          image: turandot/openssh
          name: openssh
          resources: {}
      restartPolicy: Always
status: {}
