version: '3'

services:
  guacamole:
    depends_on:
      - guacd
    environment:
      EXTENSION_PRIORITY: "*, saml"
      GUACD_HOSTNAME: guacd
      LDAP_CONFIG_BASE_DN: ${GUACAMOLE_LDAP_CONFIG_BASE_DN:?GUACAMOLE_LDAP_CONFIG_BASE_DN}
      LDAP_ENCRYPTION_METHOD: ${GUACAMOLE_LDAP_ENCRYPTION_METHOD:?GUACAMOLE_LDAP_ENCRYPTION_METHOD}
      LDAP_GROUP_BASE_DN: ${GUACAMOLE_LDAP_GROUP_BASE_DN:?GUACAMOLE_LDAP_GROUP_BASE_DN}
      LDAP_GROUP_SEARCH_FILTER: ${GUACAMOLE_LDAP_GROUP_SEARCH_FILTER:?GUACAMOLE_LDAP_GROUP_SEARCH_FILTER}
      LDAP_HOSTNAME: ${GUACAMOLE_LDAP_HOSTNAME:?GUACAMOLE_LDAP_HOSTNAME}
      LDAP_PORT: ${GUACAMOLE_LDAP_PORT:?GUACAMOLE_LDAP_PORT}
      LDAP_SEARCH_BIND_DN: ${GUACAMOLE_LDAP_SEARCH_BIND_DN:?GUACAMOLE_LDAP_SEARCH_BIND_DN}
      LDAP_SEARCH_BIND_PASSWORD: ${GUACAMOLE_LDAP_SEARCH_BIND_PASSWORD:?GUACAMOLE_LDAP_SEARCH_BIND_PASSWORD}
      LDAP_USER_BASE_DN: ${GUACAMOLE_LDAP_USER_BASE_DN:?GUACAMOLE_LDAP_USER_BASE_DN}
      POSTGRES_DATABASE: guacamole
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      POSTGRES_USER: guacamole
      SAML_CALLBACK_URL: ${GUACAMOLE_SAML_CALLBACK_URL:?GUACAMOLE_SAML_CALLBACK_URL}
      SAML_DEBUG: 'true'
      SAML_ENTITY_ID: ${GUACAMOLE_SAML_ENTITY_ID:?GUACAMOLE_SAML_ENTITY_ID}
      SAML_IDP_METADATA_URL: ${GUACAMOLE_SAML_IDP_METADATA_URL:?GUACAMOLE_SAML_IDP_METADATA_URL}
      SAML_STRICT: 'false'
    image: guacamole/guacamole:${GUACAMOLE_VERSION:?GUACAMOLE_VERSION}
    restart: unless-stopped
    volumes:
      - /opt/guacamole/ldap
      - /opt/guacamole/mysql/schema
      - /opt/guacamole/postgresql/schema
  guacd:
    image: guacamole/guacd:${GUACAMOLE_VERSION:?GUACAMOLE_VERSION}
    restart: unless-stopped
  haproxy:
    depends_on:
      - guacamole
      - keycloak
    image: haproxy:${HAPROXY_VERSION:?HAPROXY_VERSION}
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem:ro
  keycloak:
    command: start --import-realm
    depends_on:
      - openldap
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:?POSTGRES_KEYCLOAK_PASSWORD}
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER:?POSTGRES_KEYCLOAK_USER}
      KC_DB_URL_DATABASE: ${POSTGRES_KEYCLOAK_DB:?POSTGRES_KEYCLOAK_DB}
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:?KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: edge
      KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:?KEYCLOAK_ADMIN_PASSWORD}
    image: keycloak/keycloak:${KEYCLOAK_VERSION:?KEYCLOAK_VERSION}
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
  openldap:
    build: openldap
    environment:
      DEBUG_LEVEL: shell
    image: turandot/openldap
    volumes:
      - ./openldap/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    volumes_from:
      - guacamole
  openssh:
    build: openssh
    environment:
      OPENSSH_ROOT_PASSWORD: ${OPENSSH_ROOT_PASSWORD:?OPENSSH_ROOT_PASSWORD}
    image: turandot/openssh
  postgres:
    environment:
      GUACAMOLE_GROUPS: ${GUACAMOLE_GROUPS:?GUACAMOLE_GROUPS}
      POSTGRES_DB: guacamole
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      POSTGRES_KEYCLOAK_DB: ${POSTGRES_KEYCLOAK_DB:?POSTGRES_KEYCLOAK_DB}
      POSTGRES_KEYCLOAK_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:?POSTGRES_KEYCLOAK_PASSWORD}
      POSTGRES_KEYCLOAK_USER: ${POSTGRES_KEYCLOAK_USER:?POSTGRES_KEYCLOAK_USER}
      POSTGRES_USER: guacamole
    image: postgres:${POSTGRES_VERSION:?POSTGRES_VERSION}
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    #      - ./postgres/data:/var/lib/postgresql/data
    volumes_from:
      - guacamole
