name: Helm-Release

on:
  push:
    branches:
      - main

## REF: https://faun.pub/semantic-version-of-helm-charts-in-github-actions-using-conventional-commits-ce5e0a587ce8
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code                   # Checkout source code
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: lecture11
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

